Apply modifiers on environment openning
GeoGuideProject/geoguide pull request #21
Opened 2017-11-22 17:14 UTC by TiagoLisboa

2017-11-25 13:07 UTC, felipemfp requested changes

2017-11-25 13:07 UTC, felipemfp commented on geoguide/client/static/src/pageEnvironment/index.js
> +    ls["sizeModifier"] = sizeModifiereElement.value
*`sizeModifierElement`

2017-11-25 15:04 UTC, chicobentojr commented on geoguide/client/static/src/pageEnvironment/index.js
> +	let oFPointsElement = document.getElementById("onlyfilteredpoints")
I think it's better to use `onlyFilteredPointsElement`.

2017-11-27 01:14 UTC, felipemfp approved these changes
👍

2017-11-27 01:14 UTC, merged